/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 17:02:03 GMT 2018
 */

package servico.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import model.Comprador;
import model.impl.ingressos.IngressoPlateia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import servico.impl.EstrategiaDescontoPadrao;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EstrategiaDescontoPadrao_ESTest extends EstrategiaDescontoPadrao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IngressoPlateia ingressoPlateia0 = new IngressoPlateia();
      Comprador comprador0 = Comprador.IDOSO;
      EstrategiaDescontoPadrao estrategiaDescontoPadrao0 = new EstrategiaDescontoPadrao(ingressoPlateia0, comprador0);
      Double double0 = estrategiaDescontoPadrao0.calcula();
      assertEquals(150.0, (double)double0, 0.01);
  }
}
