/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 17:02:00 GMT 2018
 */

package servico.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dao.Dao;
import model.impl.Evento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import servico.impl.ServicoEvento;
import validador.Validador;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ServicoEvento_ESTest extends ServicoEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ServicoEvento servicoEvento0 = new ServicoEvento((Validador<Evento>) null, (Dao<Evento>) null);
      // Undeclared exception!
      try { 
        servicoEvento0.salva((Evento) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("servico.impl.ServicoEvento", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ServicoEvento servicoEvento0 = new ServicoEvento((Validador<Evento>) null, (Dao<Evento>) null);
      // Undeclared exception!
      try { 
        servicoEvento0.create((Evento) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("servico.impl.ServicoEvento", e);
      }
  }
}
