/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 13:09:47 GMT 2018
 */

package servico.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import servico.impl.ServicoCalculadoraDesconto;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ServicoCalculadoraDesconto_ESTest extends ServicoCalculadoraDesconto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ServicoCalculadoraDesconto servicoCalculadoraDesconto0 = new ServicoCalculadoraDesconto();
  }
}
