/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 17:01:51 GMT 2018
 */

package model.impl.ingressos;

import org.junit.Test;
import static org.junit.Assert.*;
import model.impl.ingressos.IngressoPlateiaVip;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IngressoPlateiaVip_ESTest extends IngressoPlateiaVip_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IngressoPlateiaVip ingressoPlateiaVip0 = new IngressoPlateiaVip();
      assertEquals(500, ingressoPlateiaVip0.getValor());
  }
}
