/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 17:01:14 GMT 2018
 */

package exception;

import org.junit.Test;
import static org.junit.Assert.*;
import exception.RegraNegocioException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegraNegocioException_ESTest extends RegraNegocioException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegraNegocioException regraNegocioException0 = new RegraNegocioException("CM{f*Ny.f<Dj");
  }
}
