/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 13:05:54 GMT 2018
 */

package model.impl.ingressos;

import org.junit.Test;
import static org.junit.Assert.*;
import model.impl.ingressos.IngressoPlateia;
import model.impl.ingressos.TipoIngresso;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IngressoPlateia_ESTest extends IngressoPlateia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IngressoPlateia ingressoPlateia0 = new IngressoPlateia();
      assertEquals(TipoIngresso.PLATEIA, ingressoPlateia0.getTipoIngresso());
  }
}
