/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 17:04:32 GMT 2018
 */

package model.impl.desconto;

import org.junit.Test;
import static org.junit.Assert.*;
import model.impl.desconto.EstudanteDesconto;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EstudanteDesconto_ESTest extends EstudanteDesconto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EstudanteDesconto estudanteDesconto0 = new EstudanteDesconto();
      Double double0 = estudanteDesconto0.getPercentualDeDesconto();
      assertEquals(0.5, (double)double0, 0.01);
  }
}
