/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 17:02:05 GMT 2018
 */

package model.impl.desconto;

import org.junit.Test;
import static org.junit.Assert.*;
import model.impl.desconto.OuroDesconto;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OuroDesconto_ESTest extends OuroDesconto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OuroDesconto ouroDesconto0 = new OuroDesconto();
      Double double0 = ouroDesconto0.getPercentualDeDesconto();
      assertEquals(0.75, (double)double0, 0.01);
  }
}
